---
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Create user(s)
  user:
    name: "{{ item.name }}"
    append: yes
    groups: "{{ item.groups }}"
  loop: "{{ users }}"

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
    validate_certs: False
  loop: "{{ users }}"

- name: Ensure ansible's user "ubuntu" has passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ubuntu ALL='
    line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
    
- name: Set "cron" state "started" and enabled "yes"
  service:
    name: cron
    state: started
    enabled: no  

